name: tests

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        imgtag:
          - "golang:1.9-stretch"
          - "golang:1.10-stretch"
          - "golang:1.11-buster"
          - "golang:1.12-buster"
          - "golang:1.13-buster"
          - "golang:1.14-buster"

    container: "${{matrix.imgtag}}"
    env:
      GOPATH: "${{github.workspace}}/go"
      SRCDIR: "go/src/github.com/ploxiln/oauth2_proxy"
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{env.SRCDIR}}
      - name: dependencies
        run: |
          cd $SRCDIR
          wget --no-verbose -O dep https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64
          chmod +x dep
          ./dep ensure -v
      - name: build
        run: |
          cd $SRCDIR
          go build
      - name: test
        run: |
          cd $SRCDIR
          ./test.sh
