name: tests

on:
  push:         {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  test:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        imgtag:
          - "golang:1.13-buster"
          - "golang:1.14-buster"
          - "golang:1.15-buster"

    container: "${{matrix.imgtag}}"
    env:
      GOPATH: "${{github.workspace}}/go"
      SRCDIR: "go/src/github.com/ploxiln/oauth2_proxy"
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{env.SRCDIR}}
      - name: build
        run: |
          cd $SRCDIR
          go build
      - name: test
        run: |
          cd $SRCDIR
          ./test.sh
